#pragma once

typedef int hd_error;
enum {
  HD_NO_ERROR = 0,
  HD_MEM_ALLOC_FAILED,
  HD_MEM_COPY_FAILED,
  HD_INVALID_DEVICE_INDEX,
  HD_DEVICE_ALREADY_SET,
  HD_INVALID_PIPELINE,
  HD_INVALID_POINTER,
  HD_INVALID_STRIDE,
  HD_INVALID_NBITS,
  HD_PRIOR_GPU_ERROR,
  HD_INTERNAL_GPU_ERROR,
  HD_TOO_MANY_EVENTS,
  HD_UNKNOWN_ERROR
};

